<?php
/**
 * Created by PhpStorm.
 * User: aymen
 * Date: 18/09/2018
 * Time: 13:42
 */

class Voiture extends Vehicule
{
    private static $nbVoiture = 0;

    public function freiner () {
        $this->vitesse -= 10;
    }

    public function readmeMe() {
        echo "Je suis : ".self::class."<br>";
        foreach ($this as $attribut=>$valeur) {
            echo "$attribut : $valeur<br>";
        }
    }

    public static function getNbVoitures() {
        echo "Nous avons maintenant ".self::$nbVoiture." Voitures <br>";
    }

    public function __construct($vitesse=0)
    {
        $this->vitesse = $vitesse;
        self::$nbVoiture++;
        $this->readmeMe();
    }

    public function tableauDeBord()
    {
       parent::tableauDeBord(); // TODO: Change the autogenerated stub
       echo "JE suis une voiture unique :D";
    }

    function reglageMoteur()
    {
        echo 'ook';
        // TODO: Implement reglageMoteur() method.
    }

}